Error: Cannot set CPU on the functions setCustomUserClaimsFirebase,createOrganizationAdmin,createOrganizationUser,deleteOrganizationUser,toggleUserStatusFirebase,removeAdminFromOrganizationFirebase because they are GCF gen 1
Para começar a aplicar os requisitos do token App Check nas funções chamáveis, modifique as funções para verificar os tokens válidos App Check, conforme mostrado abaixo. Depois de ativar a aplicação, todas as solicitações não verificadas serão rejeitadas.

    Instale o SDK Cloud Functions.
    Node.js (1ª geração)
    Node.js (2ª geração)
    Python (pré-lançamento)

    Atualize a dependência firebase-functions do projeto para a versão 4.0.0 ou mais recente:

npm install firebase-functions@">=4.0.0"

Ative a opção de tempo de execução de aplicação do App Check na sua função:
Node.js (1ª geração)
Node.js (2ª geração)
Python (pré-lançamento)

const { onCall } = require("firebase-functions/v2/https");

exports.yourV2CallableFunction = onCall(
  {
    enforceAppCheck: true, // Reject requests with missing or invalid App Check tokens.
  },
  (request) => {
    // request.app contains data from App Check, including the app ID.
    // Your function logic follows.
    ...
  }
);

Implante as funções novamente:

    firebase deploy --only functions

Depois que essas alterações forem implantadas, as funções chamáveis vai precisar de tokens App Check válidos. Os SDKs do cliente Cloud Functions anexam automaticamente um token App Check quando você invoca uma função chamável.