firebase deploy --only firestore
Error: Cannot understand what targets to deploy/serve. No targets in firebase.json match '--only firestore'.

Having trouble? Try firebase [command] --help

   ╭───────────────────────────────────────────────────────────────────╮
   │                                                                   │
   │                 Update available 14.4.0 → 14.5.1                  │
   │          To update to the latest version using npm, run           │
   │                   npm install -g firebase-tools                   │
   │   For other CLI management options, visit the CLI documentation   │
   │                                                                   │
   │                                                                   │
   │                                                                   │
   ╰───────────────────────────────────────────────────────────