TypeError: "" is not a function     at Object.<anonymous> (/home/user/studio/functions/index.js:553:3)     at Module._compile (node:internal/modules/cjs/loader:1529:14)     at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)     at Module.load (node:internal/modules/cjs/loader:1275:32)     at Module._load (node:internal/modules/cjs/loader:1096:12)     at Module.require (node:internal/modules/cjs/loader:1298:19)     at require (node:internal/modules/helpers:182:18)     at loadModule (/home/user/studio/functions/node_modules/firebase-functions/lib/runtime/loader.js:40:16)     at loadStack (/home/user/studio/functions/node_modules/firebase-functions/lib/runtime/loader.js:157:23)     at /home/user/studio/functions/node_modules/firebase-functions/lib/bin/firebase-functions.js:56:56
Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

Having trouble? Try firebase [command] --help