Console Error
FirebaseError: Missing or insufficient permissions.

reveja as integrações já feitas que podem ter afetado o carregamento do colaborador pois nenhuma funcionalidade está carregando